# Site settings
title: David Haoming Chen
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: David Haoming Chen
user_description: I'm a budding Computer Science student currently studying Artificial Intelligence and Computer Science at the University of Sheffield. This webpage will serve as a launchboard for my future computing related projects that I will either be a part of or will undertake. My interests lie in this field and I am pursuing tensorflow, keras and various machine learning models in the current summer of 2020.</a>
user_title: Student at University of Sheffield
email: david-chen1@hotmail.co.uk
# twitter_username: lorem_ipsum
github_username:  20dchen01
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
